package userslogs;

import config.dbConnector;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.Random;
import javax.swing.JOptionPane;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author PC15
 */
public class forgot extends javax.swing.JFrame {
    
    public forgot() {
        initComponents();
        
    }
    
   public static String hashPassword(String password) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            byte[] hashedBytes = md.digest(password.getBytes());
            StringBuilder sb = new StringBuilder();
            for (byte b : hashedBytes) {
                sb.append(String.format("%02x", b));
            }
            return sb.toString();
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException("SHA-256 algorithm not found!");
        }
    }

    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        showpassword = new javax.swing.JCheckBox();
        email = new javax.swing.JTextField();
        otpfield = new javax.swing.JTextField();
        comfirmPassword = new javax.swing.JPasswordField();
        newPassword = new javax.swing.JPasswordField();
        otpbutton = new javax.swing.JButton();
        login = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 255, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORGOT FORM");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 60, 140, 40);

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 10, 420, 0);

        showpassword.setBackground(new java.awt.Color(204, 204, 204));
        showpassword.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        showpassword.setText("show password");
        showpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(showpassword);
        showpassword.setBounds(390, 300, 120, 20);

        email.setBackground(new java.awt.Color(204, 204, 204));
        email.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 11))); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email);
        email.setBounds(200, 110, 280, 40);

        otpfield.setBackground(new java.awt.Color(204, 204, 204));
        otpfield.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "OTP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 11))); // NOI18N
        otpfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otpfieldActionPerformed(evt);
            }
        });
        jPanel1.add(otpfield);
        otpfield.setBounds(200, 160, 190, 40);

        comfirmPassword.setBackground(new java.awt.Color(204, 204, 204));
        comfirmPassword.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        comfirmPassword.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Comfirm Password"));
        comfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comfirmPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(comfirmPassword);
        comfirmPassword.setBounds(200, 260, 280, 40);

        newPassword.setBackground(new java.awt.Color(204, 204, 204));
        newPassword.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        newPassword.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "New Password"));
        newPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(newPassword);
        newPassword.setBounds(200, 210, 280, 40);

        otpbutton.setText("Send OTP");
        otpbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otpbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(otpbutton);
        otpbutton.setBounds(400, 160, 110, 40);

        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login);
        login.setBounds(200, 340, 100, 30);

        reset.setText("Reset Password");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset);
        reset.setBounds(360, 340, 160, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userimages/attachment_63634065.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-90, 0, 680, 450);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(410, 0, 410, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        
    }//GEN-LAST:event_emailActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
             String userEmail = email.getText().trim();
        String enteredOtp = otpfield.getText().trim();
        String newPass = new String(newPassword.getPassword()).trim();
        String confirmPass = new String(comfirmPassword.getPassword()).trim();

        if (userEmail.isEmpty() || enteredOtp.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter both email and OTP.");
            return;
        }

        if (newPass.isEmpty() || confirmPass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in both password fields.");
            return;
        }

        if (!newPass.equals(confirmPass)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match.");
            return;
        }

        try {
            dbConnector dbc = new dbConnector();
            Connection conn = dbc.getConnection();

            String sql = "SELECT * FROM otp_requests WHERE user_email = ? AND otp_code = ? AND is_used = 0 AND expiry_time > NOW() ORDER BY id DESC LIMIT 1";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, userEmail);
            pst.setString(2, enteredOtp);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                String hashedPassword = hashPassword(newPass);

                String updatePasswordSql = "UPDATE tbl_user SET u_password = ? WHERE u_email = ?";
                PreparedStatement updatePst = conn.prepareStatement(updatePasswordSql);
                updatePst.setString(1, hashedPassword);
                updatePst.setString(2, userEmail);
                updatePst.executeUpdate();
                updatePst.close();

                String markUsedSql = "UPDATE otp_requests SET is_used = 1 WHERE id = ?";
                PreparedStatement markUsedPst = conn.prepareStatement(markUsedSql);
                markUsedPst.setInt(1, rs.getInt("id"));
                markUsedPst.executeUpdate();
                markUsedPst.close();

                JOptionPane.showMessageDialog(this, "Password reset successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Invalid or expired OTP.");
            }

            rs.close();
            pst.close();
            conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
}

    }//GEN-LAST:event_resetActionPerformed

    private void comfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comfirmPasswordActionPerformed

    private void showpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpasswordActionPerformed
     
    }//GEN-LAST:event_showpasswordActionPerformed

    private void newPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPasswordActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
       
    }//GEN-LAST:event_loginActionPerformed

    private void otpfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otpfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otpfieldActionPerformed

    private void otpbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otpbuttonActionPerformed
     String userEmail = email.getText().trim();

    if (userEmail.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter your email first.");
        return;
    }

    // Generate 6-digit OTP
    String otp = String.format("%06d", new Random().nextInt(999999));

    // Send OTP via email
    boolean sent = EmailSender.sendOtpEmail(userEmail, otp);

    if (sent) {
        try {
            dbConnector dbc = new dbConnector();
            Connection conn = dbc.getConnection();

            // Set expiry time in Java (10 minutes from now)
            LocalDateTime expiryTime = LocalDateTime.now().plusMinutes(10);
            Timestamp expiryTimestamp = Timestamp.valueOf(expiryTime);

            String sql = "INSERT INTO otp_requests (user_email, otp_code, expiry_time, is_used) VALUES (?, ?, ?, 0)";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, userEmail);
            pst.setString(2, otp);
            pst.setTimestamp(3, expiryTimestamp);
            pst.executeUpdate();
            pst.close();
            conn.close();

            JOptionPane.showMessageDialog(this, "OTP sent successfully to your email.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Failed to save OTP: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(this, "Failed to send OTP email.");
    }
    }//GEN-LAST:event_otpbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField comfirmPassword;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField newPassword;
    private javax.swing.JButton otpbutton;
    private javax.swing.JTextField otpfield;
    private javax.swing.JButton reset;
    private javax.swing.JCheckBox showpassword;
    // End of variables declaration//GEN-END:variables
}
