/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userslogs;

import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import config.dbConnector;
import java.sql.ResultSet;
import java.sql.SQLException;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author SCC-COLLEGE
 */
public class Log extends javax.swing.JInternalFrame {

    /**
     * Creates new form Userpage
     */
    public Log() {
        initComponents();  
        displayLogsByAction("All");
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);

        searchBar.setOpaque(false);
        searchBar.setBackground(new Color(0, 0, 0, 0));
    }

    public void displayLogsByAction(String action) {
    try {
        dbConnector dbc = new dbConnector();
        
        // Modify the SQL query to handle both Login/Logout or All actions
        String query = "";
        
        if (action.equals("All")) {
            query = "SELECT l.l_id, u.u_fname, u.u_type, l.l_action, l.l_timestamp " +
                    "FROM tbl_logs l " +
                    "JOIN tbl_users u ON l.u_id = u.u_id " +
                    "ORDER BY l.l_timestamp DESC";  // Show all logs
        } else {
            query = "SELECT l.l_id, u.u_fname, u.u_type, l.l_action, l.l_timestamp " +
                    "FROM tbl_logs l " +
                    "JOIN tbl_users u ON l.u_id = u.u_id " +
                    "WHERE l.l_action = ? " +  // Filter based on action type
                    "ORDER BY l.l_timestamp DESC";
        }
        
        java.sql.PreparedStatement pst = dbc.getConnection().prepareStatement(query);
        
        if (!action.equals("All")) {
            pst.setString(1, action);  // Pass Login or Logout for filtering
        }
        
        ResultSet rs = pst.executeQuery();
        userTable.setModel(DbUtils.resultSetToTableModel(rs));
        
        // Set table column headers
        userTable.getColumnModel().getColumn(0).setHeaderValue("Log ID");
        userTable.getColumnModel().getColumn(1).setHeaderValue("User Name");
        userTable.getColumnModel().getColumn(2).setHeaderValue("User Type");
        userTable.getColumnModel().getColumn(3).setHeaderValue("Action");
        userTable.getColumnModel().getColumn(4).setHeaderValue("Timestamp");
    } catch (SQLException ex) {
        System.out.println("SQLException occurred: " + ex.getMessage());
        ex.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        searchBar = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        login = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        loginFailed = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        searchBar.setMinimumSize(new java.awt.Dimension(8, 20));
        searchBar.setPreferredSize(new java.awt.Dimension(8, 20));
        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarActionPerformed(evt);
            }
        });
        jPanel1.add(searchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 240, 23));

        searchButton.setText("SEARCH");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        loginFailed.setText("Login Failed");
        loginFailed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginFailedActionPerformed(evt);
            }
        });
        jPanel1.add(loginFailed, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(userTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 520, 250));

        title.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        title.setText("Logs Activity");
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Untitled Project.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBarActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String keyword = searchBar.getText().trim();
    try {
        dbConnector dbc = new dbConnector();
        String query = "SELECT l.l_id, l.u_id, u.u_fn, l.l_action, l.l_timestamp " +
                       "FROM tbl_logs l " +
                       "JOIN tbl_user u ON l.u_id = u.u_id " +
                       "WHERE l.l_id LIKE '%" + keyword + "%' " +
                       "OR l.u_id LIKE '%" + keyword + "%' " +
                       "OR u.u_fname LIKE '%" + keyword + "%' " +
                       "OR l.l_action LIKE '%" + keyword + "%' " +
                       "OR l.l_timestamp LIKE '%" + keyword + "%'";
        ResultSet rs = dbc.getData(query);
        
        if (!rs.isBeforeFirst()) {
            javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
            model.setColumnIdentifiers(new String[]{"Message"});
            model.addRow(new Object[]{"No results found for \"" + keyword + "\""});
            userTable.setModel(model);
        } else {
            userTable.setModel(DbUtils.resultSetToTableModel(rs));
            userTable.getColumnModel().getColumn(0).setHeaderValue("Log ID");
            userTable.getColumnModel().getColumn(1).setHeaderValue("User Name");
            userTable.getColumnModel().getColumn(2).setHeaderValue("User Type");
            userTable.getColumnModel().getColumn(3).setHeaderValue("Action");
            userTable.getColumnModel().getColumn(4).setHeaderValue("Timestamp");
        }
    } catch (SQLException ex) {
        System.out.println("SQLException occurred during search: " + ex.getMessage());
        ex.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        displayLogsByAction("Login");
    }//GEN-LAST:event_loginActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        displayLogsByAction("Logout");
    }//GEN-LAST:event_logoutActionPerformed

    private void loginFailedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginFailedActionPerformed
        displayLogsByAction("Login failed");
    }//GEN-LAST:event_loginFailedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton login;
    private javax.swing.JButton loginFailed;
    private javax.swing.JButton logout;
    private javax.swing.JTextField searchBar;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel title;
    public javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
